#!/usr/bin/env sh
# Рукописная копия того, что порождает генератор.
#
# ОТКУДА КЛАСС. Случай из живого проекта владельца 2026-09-15: тип фронта написан руками, в нём
# объявлено поле, которого на сервере нет. `tsc` — судья, который врать не умеет, — согласился с
# бумажкой, а не с сервером, и промолчал. Правило «типы выводятся из schema.d.ts» было записано
# в шапке того же файла, соседние модули его соблюдали.
#
# Класс шире TypeScript: где-то лежит ПОРОЖДЁННЫЙ файл (истина), рядом рукописная копия тех же
# имён. С этого момента компилятор сверяет код с копией, а не с истиной.
#
# ЗАМЕР, А НЕ ГЕЙТ. Прежде чем заводить запись, надо узнать, часто ли это. Два прошлых кандидата
# замер убил: `.mcp.json` без обёртки — 1 случай из 43.
LIST="${1:?дай файл со списком репозиториев}"
HIT=0; SEEN=0; NOGEN=0
while IFS= read -r REPO; do
  [ -z "$REPO" ] && continue
  D=$(mktemp -d)
  timeout 120 git clone -q --depth 1 "https://github.com/$REPO" "$D" 2>/dev/null || { rm -rf "$D"; continue; }
  # Порождённый файл опознаём по метке генератора, а не по имени: имена у всех разные.
  GEN=$(grep -rlE "openapi-typescript|DO NOT EDIT|auto-generated|autogenerated|Code generated" \
        --include='*.d.ts' --include='*.gen.ts' --include='*.generated.ts' "$D" 2>/dev/null | head -3)
  [ -z "$GEN" ] && { NOGEN=$((NOGEN+1)); rm -rf "$D"; continue; }
  SEEN=$((SEEN+1))
  # Имена из порождённого файла: интерфейсы и псевдонимы верхнего уровня.
  NAMES=$(printf '%s\n' "$GEN" | while IFS= read -r G; do
      sed -n 's/^[[:space:]]*\(export[[:space:]]\{1,\}\)\{0,1\}\(interface\|type\)[[:space:]]\{1,\}\([A-Z][A-Za-z0-9_]*\).*/\3/p' "$G"
    done | sort -u | head -60)
  [ -z "$NAMES" ] && { rm -rf "$D"; continue; }
  FOUND=""
  for N in $NAMES; do
    # Та же сущность, объявленная руками в НЕ порождённом файле.
    M=$(grep -rlE "^[[:space:]]*(export[[:space:]]+)?(interface|type)[[:space:]]+$N\b" \
        --include='*.ts' --include='*.tsx' "$D" 2>/dev/null \
        | grep -vFf /dev/stdin <<EOF2 2>/dev/null || true
$GEN
EOF2
)
    [ -n "$M" ] && FOUND="$FOUND$N "
  done
  if [ -n "$FOUND" ]; then HIT=$((HIT+1)); echo "✘ $REPO: руками объявлены те же имена — $FOUND"; fi
  rm -rf "$D"
done < "$LIST"
echo "репозиториев с порождёнными типами: $SEEN · из них с рукописной копией: $HIT · без генератора: $NOGEN"
