#!/usr/bin/env sh
# Что сканирующие проверки не читают. Общий список: разъехавшись по шести проверкам, он
# однажды окажется полным в одной и дырявым в другой.
#
# ПОЧЕМУ ЭТО ВАЖНЕЕ, ЧЕМ КАЖЕТСЯ. На настоящем проекте из 36 тысяч файлов 1722 находки из 1831
# пришли из чужого кода в окружении. Гейт, который на 94% состоит из чужих нарушений, читать
# никто не будет — его выключат.

SKIP_NAMES=".git .aqk node_modules .venv venv env __pycache__ .mypy_cache .pytest_cache
.tox .ruff_cache site-packages dist build target out .next .nuxt .svelte-kit coverage
htmlcov vendor bower_components .gradle .idea .vscode
playwright-report test-results storybook-static .turbo .cache .parcel-cache
migrations"

# Образцы гейтов — искусственный код по построению: красный сломан нарочно, зелёный бывает
# вырожденным (двести одинаковых строк, чтобы показать предел размера). Сканировать их — значит
# ловить то, что положил не человек. Исключение снимается, когда цель проверки — сам образец.
sample_dirs() {
  case "${1:-}" in
    */red|*/red/|*/green|*/green/) : ;;
    *) printf 'red green' ;;
  esac
}

# Расширения, где `print` и маркеры долга — конструкции языка, а не текст. Проверять по ним
# файлы настроек, разметку и отчёты бессмысленно: там те же слова означают другое.
CODE_EXT="py js jsx ts tsx vue go rb java cs php rs kt swift scala"

include_code() {
  for E in $CODE_EXT; do printf -- '--include=*.%s ' "$E"; done
}

# Сгенерированный файл не правят руками — предъявлять его размер или сложность человеку
# бессмысленно и вредно: он выключит проверку целиком.
# Опознаём по общепринятой шапке в первых пяти строках.
is_generated() {
  head -5 "$1" 2>/dev/null | grep -qiE '@generated|do not edit|autogenerated|auto-generated|generated by|сгенерирован'
}

# Для grep: --exclude-dir на каждое имя.
skip_grep() {
  for N in $SKIP_NAMES $(sample_dirs "${1:-}"); do printf -- '--exclude-dir=%s ' "$N"; done
}

# Для find: -name X -prune -o … Красные образцы исключаются отдельно, только когда цель
# проверки — не сам образец.
skip_find() {
  for N in $SKIP_NAMES $(sample_dirs "${1:-}"); do printf -- '-name %s -prune -o ' "$N"; done
}
